FROM node:26-alpine AS build
WORKDIR /app
COPY package.json package-lock.json* ./
RUN --mount=type=cache,target=/root/.npm \
    npm ci
COPY . .
ARG VITE_BASE=/admin/
ENV VITE_BASE=${VITE_BASE}
ENV VITE_PB_URL=/
ENV VITE_ADMIN=true
RUN npm run build

FROM nginx:1.31.2-alpine
COPY docker/nginx.cms.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html/admin
EXPOSE 5175
